networks:
  wirehole:
    name: wirehole
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  wg-easy:
    depends_on: [pihole]
    environment:
      - WG_HOST=jordanking.duckdns.org
      - PASSWORD=Ngoc248*
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.6.0.x
      - WG_DEFAULT_DNS=10.2.0.100
      - WG_ALLOWED_IPS=192.168.24.0/24

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /home/pi/pivpn:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 10.2.0.100
    networks:
      wirehole:
        ipv4_address: 10.2.0.3

  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: pihole
    domainname: pihole.local
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8081:80/tcp
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.24.24
      - TZ=Asia/Ho_Chi_Minh
      - WEBPASSWORD=Ngoc248*
      - WEBTHEME=default-dark
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
    networks:
      wirehole:
        ipv4_address: 10.2.0.100
