name: tools

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/my.cnf
      - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
  # rabbitmq2:
  #   image: rabbitmq:3-management-alpine
  #   restart: unless-stopped
  #   ports:
  #     - 5673:5672
  #     - 15673:15672
  redis:
    image: redis:7.0
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  mysql:
