name: tools

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/my.cnf
      - mysql:/var/lib/mysql
  redis:
    image: redis:7.0
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  mysql:
