services:
  cubable-core:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - backend
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      start_period: 5s
      interval: 5s
      retries: 10
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - mysql:/var/lib/mysql
    networks:
      - backend
  db-migrations:
    build: .
    command:
      [
        "./docker/wait-for-it/wait-for-it.sh",
        "db:3306",
        "--",
        "npm",
        "run",
        "migrate",
      ]
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - migrate
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend
  redis:
    image: redis:7.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      start_period: 5s
      interval: 5s
      retries: 10
    ports:
      - 6379:6379
    networks:
      - backend

volumes:
  mysql:

networks:
  backend:
