version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki:/etc/loki
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
      - ./promtail/:/etc/promtail
    # ports:
    # - "1514:1514" # this is only need if you going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    user: "1001"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - loki
