services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    ports:
      - 3004:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  uptime-kuma:
    external: false
